// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWk8vc0wEM3kHYDuswdVpm_ZSRy6KgGrI',
    appId: '1:87797564564:web:0cda0f635d6097ef29e081',
    messagingSenderId: '87797564564',
    projectId: 'alpha-store-5d896',
    authDomain: 'alpha-store-5d896.firebaseapp.com',
    databaseURL: 'https://alpha-store-5d896-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'alpha-store-5d896.appspot.com',
    measurementId: 'G-YY3X66S24R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLwGoixXmCFOg_M3Faet54BWZQIhafQrY',
    appId: '1:87797564564:android:01f064665eae665b29e081',
    messagingSenderId: '87797564564',
    projectId: 'alpha-store-5d896',
    databaseURL: 'https://alpha-store-5d896-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'alpha-store-5d896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLTOeRajKzOgrnDQKOzL3295mzWOL7m5U',
    appId: '1:87797564564:ios:95a3ea0dde66afe829e081',
    messagingSenderId: '87797564564',
    projectId: 'alpha-store-5d896',
    databaseURL: 'https://alpha-store-5d896-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'alpha-store-5d896.appspot.com',
    iosBundleId: 'com.example.quotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLTOeRajKzOgrnDQKOzL3295mzWOL7m5U',
    appId: '1:87797564564:ios:4692c294e2a564de29e081',
    messagingSenderId: '87797564564',
    projectId: 'alpha-store-5d896',
    databaseURL: 'https://alpha-store-5d896-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'alpha-store-5d896.appspot.com',
    iosBundleId: 'com.example.quotes.RunnerTests',
  );
}
