// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzP4WKutZxTuRgkBRt-AIWPslP5w1SerA',
    appId: '1:826651355544:web:bd70d5165a28aa04ed63ed',
    messagingSenderId: '826651355544',
    projectId: 'friendshipquotes-184b2',
    authDomain: 'friendshipquotes-184b2.firebaseapp.com',
    storageBucket: 'friendshipquotes-184b2.appspot.com',
    measurementId: 'G-X7STH795JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcJKcamVnmLZ3YcsiHMzECe7sSDN6giWQ',
    appId: '1:826651355544:android:ad25bfdcd701b075ed63ed',
    messagingSenderId: '826651355544',
    projectId: 'friendshipquotes-184b2',
    storageBucket: 'friendshipquotes-184b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIkS7_VcVk9Yj57NEGbOKvVkZ4xKsGbuo',
    appId: '1:826651355544:ios:c8ba82801b10aba2ed63ed',
    messagingSenderId: '826651355544',
    projectId: 'friendshipquotes-184b2',
    storageBucket: 'friendshipquotes-184b2.appspot.com',
    iosBundleId: 'com.example.quotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIkS7_VcVk9Yj57NEGbOKvVkZ4xKsGbuo',
    appId: '1:826651355544:ios:fa8fc3443ee48f7bed63ed',
    messagingSenderId: '826651355544',
    projectId: 'friendshipquotes-184b2',
    storageBucket: 'friendshipquotes-184b2.appspot.com',
    iosBundleId: 'com.example.quotes.RunnerTests',
  );
}
